# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1acqAKYhGYFyXJxCjredJ8vsKgS62XTcp
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df= pd.read_csv("world_population.csv")

df

pd.set_option('display.float_format', lambda x: '%.2f' % x)

df.info()

df.describe()

df.isnull().sum()

df.nunique()

df.sort_values(by='World Population Percentage', ascending=False).head()

df.corr()

sns.heatmap(df.corr(),annot=True)

plt.rcParams['figure.figsize']=(30,10)
plt.show()

df2=df.groupby('Continent').mean().sort_values(by='2022 Population', ascending= False)
df2

df[df['Continent'].str.contains('Oceania')]

df3= df2[['1970 Population','1980 Population','1990 Population', '2000 Population','2010 Population','2015 Population','2020 Population','2022 Population']]
df3

df4=df3.transpose()

df4.plot()

"""**Box plot for Outliers**




"""

df.boxplot()