# -*- coding: utf-8 -*-
"""Copy of DataCleaning_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZC2aHUqAfqyGItlWNBMq4N-FrPGs7sQ
"""

#Importing Libraries
import pandas as pd
import numpy as np

#Reading a data
df=pd.read_csv('PD 2024 Wk 1 Input.csv')
df

#Removing duplicates
df=df.drop_duplicates()

#Splitting Address into Date, Flight_Num, Location, Class, and Price
df[['Date','Flight_Num','Location','Class','Price']]=df['Flight Details'].str.split('//',expand=True)
#Dropping Flight Details column which has already been splitted
df=df.drop(columns='Flight Details')
df

#Further Splitting Location from Flight Details to 'From'and 'To'
df[['From','To']]=df['Location'].str.split('-', expand=True)
#Dropping Location which has been splitted to 'From'and 'To'
df=df.drop(columns='Location')
df

#Replacing Flow Card to Yes if 1 and No if 0
df['Flow Card?']=df['Flow Card?'].replace(1,'Yes')
df['Flow Card?']=df['Flow Card?'].replace(0,'No')
df

#Converting Date to data format
df['Date'] = pd.to_datetime(df['Date'])
df

#Converting Price to numeric types so that we can perform round function to convert it to decimal value
df['Price'] = pd.to_numeric(df['Price'])
#Performing round function and converting to decimal value
df['Price']=df['Price'].apply(lambda x: round(x))

#Filtering dataframe wtih Yes Flow Card
df_yes=df[df['Flow Card?']== "Yes"]
df_yes
#Exporting the data frame with yes Flow Card to csv file
df_yes.to_csv('FlowCardYesOutput', sep=',', index=False, encoding='utf-8')

#Filtering dataframe wtih No Flow Card
df_no=df[df['Flow Card?']== "No"]
df_no
#Exporting the data frame with yes Flow Card to csv file
df_no.to_csv('FlowCardNoOutput', sep=',', index=False, encoding='utf-8')